theme: jekyll-theme-architect
title: ALL ABOUT TOYS! 
image: !(Logo)(/images/logo.png)
description: Our beautiful wooden toys will happily engage your children while providing endless opportunities for open-ended play!
